# Default Pipeline Configuration

pipeline:
  # Pipeline stages
  stages:
    - preprocess
    - train
    - evaluate
    - generate
  
  # Stage-specific settings
  preprocess:
    clean_data: true
    tokenize: true
    create_splits: true
  
  train:
    resume: true  # Resume from checkpoint if available
    validate: true  # Run validation during training
    save_checkpoints: true
  
  evaluate:
    metrics:
      - loss
      - perplexity
    generate_samples: true
    num_samples: 5
  
  generate:
    max_length: 100
    temperature: 0.8
    top_k: 40
    top_p: 0.9
    num_return_sequences: 1
    seed_text: "The" 