# No @package directive needed here

# Default Hugging Face Tokenizer Configuration

_target_: transformers.AutoTokenizer.from_pretrained

# Specify the model name or path for the tokenizer
# See: https://huggingface.co/models
pretrained_model_name_or_path: "gpt2"

# Optional arguments for AutoTokenizer.from_pretrained:
use_fast: true # Prefer fast tokenizers if available
# add_prefix_space: false # Common for GPT-2 style models
# trust_remote_code: false # Set to true only if you trust the source 