# conf/config.yaml - Main Hydra configuration file

# @package _global_

defaults:
  # Specify configuration groups to compose.
  # The order matters; later entries override earlier ones.
  - experiment: null      # Expect override from command line or specific config
  - model: transformer
  - training: default
  - data: got_char
  - optimizer: adamw
  - scheduler: cosine # Revert to match available file
  - callbacks: default    # Default callbacks configuration
  # - tokenizer: default_hf # REMOVE tokenizer group
  - _self_              # Allows defining variables directly in this file

# Example top-level configuration parameters (optional)
# These could also live in their own group files (e.g., conf/paths/default.yaml)
# paths:
#   # Default output directory pattern
#   output_dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}" # Hydra automatically sets this based on hydra.run.dir
#   # Example: Absolute path (use with caution)
#   # data_root: /path/to/datasets 

# General settings
project_name: "Craft"
experiment_name: "default_experiment" # Add experiment name field

# Add other top-level or default settings as needed 

# Configuration for data handling
data: ??? # Ensure this is resolved by defaults

# Configuration for tokenizer (placeholder)
# tokenizer: ??? # REMOVE tokenizer placeholder

# Configuration for the trainer 

# General Run Settings
seed: 42
# Remove checkpoint_dir - will be constructed in script from hydra.run.dir
log_level: "INFO"
force_cpu: False
resume_from: null # Can be set to "latest" or a specific path/to/checkpoint.pt via command line

# Hydra settings (can be overridden)
hydra:
  output_subdir: .hydra
  run:
    # Use original CWD as the base for relative paths in config
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True # Change CWD to the output directory for the run
  # Explicitly configure job logging to ensure console output
  job_logging:
    # Define formatters (using a simple one for now)
    formatters:
      simple:
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    # Define handlers
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO 
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log # Use default log file name pattern
        level: INFO
    # Configure the root logger
    root:
      level: INFO
      handlers: [console, file] # Make sure console is included
    # Disable Hydra's default logger configs if they conflict
    disable_existing_loggers: false 

# Add a new group for generation parameters
generation:
  start_prompt: "The meaning of life is\n"
  max_new_tokens: 200
  temperature: 0.8
  top_k: null # null corresponds to Python None, or you can set an integer like 50 