# conf/callbacks/default.yaml
# Default configuration for callbacks.
# This file being empty or containing only comments means that by default,
# no callbacks are loaded unless overridden.
#
# Example of adding a callback here:
# my_callback_name:
#   _target_: src.callbacks.MyCallback
#   some_param: value

# For now, keep it empty or add basic settings if needed
# callbacks_list: [] # REMOVED 

tensorboard:
  _target_: craft.training.callbacks.TensorBoardLogger
  # log_dir is now set dynamically in train_commands.py relative to Hydra output 