# conf/callbacks/default.yaml
# Default configuration for callbacks.
# This file being empty or containing only comments means that by default,
# no callbacks are loaded unless overridden.
#
# Example of adding a callback here:
# my_callback_name:
#   _target_: src.callbacks.MyCallback
#   some_param: value

# For now, keep it empty or add basic settings if needed
# callbacks_list: [] # REMOVED 

tensorboard:
  _target_: craft.training.callbacks.TensorBoardLogger
  # Use Hydra interpolation to set the log directory relative to the run output path
  log_dir: ${hydra:run.dir}/tensorboard 

# Remove the checkpoint entry entirely
# checkpoint: 
#   pass 

sample_generation:
  _target_: craft.training.callbacks.SampleGenerationCallback
  # time_sample_interval_seconds: 300 # Inherited from training config by default
  # sample_steps_interval: 1000 # Or sample every N steps
  # num_samples: 1 # Number of samples to generate each time
  # prompt: "The night is dark and" # Inherited from training config by default
  # max_new_tokens: 100 # Inherited from training config by default
  # temperature: 0.8 # Inherited from training config by default 