# Base configuration for ChatGoT

defaults:
  - _self_
  - models/gpt2_small
  - training/default
  - data/default
  - pipeline/default

# Project metadata
project:
  name: ChatGoT
  version: 0.1.0
  description: Character-level GPT for Game of Thrones Text Generation

# System configuration
system:
  seed: 42
  log_level: INFO
  device: auto  # 'auto', 'cpu', 'cuda', 'cuda:0', etc.
  dtype: float32  # 'float32', 'float16', 'bfloat16'
  num_workers: 4  # Number of workers for data loading
  pin_memory: true  # Use pinned memory for faster data loading

# Paths
paths:
  # Data paths
  data_dir: data
  raw_data: ${paths.data_dir}/game_of_thrones_dataset.txt
  data_file: ${paths.raw_data}  # Explicitly set data_file for processor.py
  processed_data_dir: processed_data
  processed_data: ${paths.processed_data_dir}/got_char_data.pkl
  analysis_dir: ${paths.processed_data_dir}/analysis
  
  # Model paths
  models_dir: models
  checkpoint_dir: checkpoints
  
  # Output paths
  output_dir: runs/${now:%Y-%m-%d}/${experiment.name}
  log_dir: ${paths.output_dir}/logs
  
  # Artifacts
  artifacts_dir: ${paths.output_dir}/artifacts

# Experiment tracking
experiment:
  name: default
  tags: []
  track: true  # Whether to track the experiment
  tracking_uri: mlruns  # MLflow tracking URI 