# conf/training/default.yaml
epochs: 5 # Set to 5 epochs
use_amp: True
gradient_accumulation_steps: 1 # Match previous high-performance run
max_grad_norm: 1.0
log_interval: 50 # Log every 50 steps
save_interval: 1 # Save checkpoint every N epochs
time_save_interval_minutes: 5 # Save checkpoint every N minutes (0 or null to disable)
compile_model: False
activation_checkpointing: False
torch_compile: False # Add default for torch.compile flag

# Sampling configuration (used during timed saves)
sample_max_new_tokens: 100
sample_temperature: 0.8
sample_start_text: "The meaning of life is"

# Generation config used by Trainer._generate_sample_and_log
generation:
  start_prompt: "The night is dark and "
  max_new_tokens: 150
  temperature: 0.8
  top_k: null 