# conf/training/minimal_test.yaml

# Inherit from default training settings
_target_: src.training.base.LanguageModelTrainerConfig
_recursive_: false # Prevent recursive instantiation if using complex types

# Override parameters for a minimal test run
epochs: 1           # Run for only 1 epoch (or set max_steps)
max_steps: 10       # Limit to only 10 training steps

# Adjust logging and saving for short run
log_interval: 50     # Log every 50 steps (restored from 1)
save_interval: 0    # Disable epoch-based saving
time_save_interval_minutes: 0 # Disable time-based saving

# Keep other settings from default or override if needed
use_amp: True
gradient_accumulation_steps: 1
max_grad_norm: 1.0
compile_model: False
activation_checkpointing: False
torch_compile: False

# Sampling settings (less relevant for short run, keep defaults)
sample_max_new_tokens: 100
sample_temperature: 0.8
sample_start_text: "The meaning of life is"

# Generation config (keep defaults)
generation:
  start_prompt: "The night is dark and "
  max_new_tokens: 150
  temperature: 0.8
  top_k: null 