#!/usr/bin/env python
"""Entry point for Craft CLI."""
import os
import sys

# Add the project root to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.cli.run import app

if __name__ == "__main__":
    app() 