_target_: torch.optim.lr_scheduler.CosineAnnealingLR
# T_max MUST be overridden in the experiment config or calculated dynamically.
# Providing a default here is likely incorrect.
T_max: ???
eta_min: 0 # Default minimum learning rate 